/* Generated by web/scripts/gen-types.mjs from `wosarcher schema`. Do not edit. */

export type Detail = string
export type Error = string
export type Data = string
export type Name = string
export type ChunkId = string
export type Passthrough = boolean
export type Prefilter = (number | null)
export type QueryId = string
export type BlockIds = string[]
export type ChunkId1 = string
export type HeadingPath = string[]
export type PageId = (string | null)
export type Position = number
export type SourceId = string
export type Text = string
export type Display = (number | null)
export type KeptInQuery = (number | null)
export type Kind = ("cited" | "source_cap" | "budget" | "kept" | "query_cap" | "below_threshold" | "prefiltered" | "pending")
export type N = (number | null)
export type QueryId1 = (string | null)
export type Rank = (number | null)
export type Ranked = (number | null)
export type TokensLeft = (number | null)
export type TokensNeeded = (number | null)
export type Display1 = (number | null)
export type QueryId2 = string
export type State = ("not_in_results" | "prefiltered" | "pending" | "below_threshold" | "query_cap" | "other_query" | "kept")
export type Chunks = Chunk[]
export type Duplicates = number
export type InputTokens = number
export type OutputTokens = number
export type Text1 = string
export type BudgetTokens = number
export type BlockIds1 = string[]
export type ChunkId2 = string
export type Display2 = (number | null)
export type HeadingPath1 = string[]
export type N1 = number
export type PageId1 = (string | null)
export type QueryId3 = string
export type Scorer = string
export type SourceId1 = string
export type Text2 = string
export type Passages = Passage[]
export type Query = string
export type Author = (string | null)
export type Kind1 = ("web" | "file")
export type Published = (string | null)
export type SourceId2 = string
export type Title = string
export type Uri = string
export type Sources = Source[]
export type UsedTokens = number
export type Description = string
export type Name1 = string
export type ContextTokens = (number | "auto")
export type GapContextTokens = (number | "auto")
export type MaxPages = number
export type PassagesPerQuery = number
export type QueriesPerRound = number
export type ResultsPerQuery = number
export type Rounds = number
export type SubQueries = number
export type Words = (number | null)
export type GpuPolicy = ("shared" | "exclusive")
export type BaseUrl = string
export type Block = string
export type ContextWindow = (number | null)
export type Device = (string | null)
export type Error1 = (string | null)
export type LatencyMs = (number | null)
export type Model = (string | null)
export type Note = (string | null)
export type Provider = string
export type Release = ("none" | "llama-swap" | "ollama")
export type Status = ("ok" | "failed" | "built-in")
export type Unload = ("yes" | "no" | "n/a")
export type Providers = ProviderHealth[]
export type Warnings = string[]
export type Dimension = number
export type Model1 = string
export type Item = string
export type Reason = string
export type Failures = Skipped[]
export type Format = ("markdown" | "pdf-ingest")
export type QueryIds = string[]
export type Rank1 = number
export type Round = number
export type Text3 = string
export type Truncated = boolean
export type Pages = Page[]
export type Unfetched = number
export type From = ("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write")
export type Profile = (string | null)
export type Set = string[]
export type CitationMarker = (("numeric" | "superscript" | "author-year") | null)
export type Language = (string | null)
export type ReferenceStyle = (string | null)
export type Tone = (string | null)
export type ToneInstructions = (string | null)
export type Words1 = (number | null)
export type Note1 = string
export type Id = string
export type Round1 = number
export type Text4 = string
export type Queries = Query1[]
export type Round2 = number
export type Stop = boolean
export type RunId = string
export type Seq = number
export type Stage = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts = string
export type Type = "gap.ready"
export type Note2 = string
export type Queries1 = Query1[]
export type Stop1 = boolean
export type Blocks = string[]
export type CheckedAt = (string | null)
export type Detail1 = string
export type Device1 = (string | null)
export type LatencyMs1 = (number | null)
export type Model2 = (string | null)
export type Provider1 = string
export type Release1 = ("none" | "llama-swap" | "ollama")
export type Role = string
export type Status1 = ("ok" | "degraded" | "down" | "skipped" | "unchecked")
export type Url = string
export type Checks = ProviderCheck[]
export type GpuPolicy1 = ("shared" | "exclusive")
export type Profile1 = string
export type Warnings1 = string[]
export type QueryIds1 = string[]
export type Rank2 = number
export type Round3 = number
export type Snippet = string
export type Title1 = string
export type Url1 = string
export type QueryIds2 = string[]
export type Title2 = string
export type Url2 = string
export type RunId1 = string
export type Seq1 = number
export type Stage1 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts1 = string
export type Type1 = "hit.found"
export type ChunkId3 = string
export type Display3 = (number | null)
export type HeadingPath2 = string[]
export type SourceId3 = string
export type Text5 = string
export type Title3 = string
export type Uri1 = string
export type Pages1 = Page[]
export type Skipped1 = Skipped[]
export type AttemptsLeft = (number | null)
export type Detail2 = string
export type Error2 = string
export type RetryAfter = (number | null)
export type Password = string
export type Content = string
export type Role1 = ("system" | "user" | "assistant")
export type Reason1 = string
export type Url3 = string
export type RunId2 = string
export type Seq2 = number
export type Stage2 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts2 = string
export type Type2 = "page.failed"
export type Cached = boolean
export type Chars = number
export type Round4 = number
export type SourceId4 = string
export type Title4 = string
export type Url4 = string
export type RunId3 = string
export type Seq3 = number
export type Stage3 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts3 = string
export type Type3 = "page.fetched"
export type Kept = number
export type Passages1 = KeptPassage[]
export type QueryId4 = string
export type Scored = number
export type Scorer1 = string
export type ThresholdDisplay = (number | null)
export type RunId4 = string
export type Seq4 = number
export type Stage4 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts4 = string
export type Type4 = "passages.scored"
export type Queries2 = Query1[]
export type Warnings2 = string[]
export type Queries3 = Query1[]
export type RunId5 = string
export type Seq5 = number
export type Stage5 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts5 = string
export type Type5 = "plan.ready"
export type Candidates = Candidate[]
export type Method = ("embeddings" | "bm25" | "none")
export type Warnings3 = string[]
export type Active = boolean
export type ContextWindow1 = (number | null)
export type Description1 = string
export type MaxOutputTokens = (number | null)
export type Name2 = string
export type PromptReserveTokens = (number | null)
export type Source1 = ("builtin" | "user")
export type Kept1 = number
export type ChunkId4 = string
export type Display4 = (number | null)
export type Dropped = (("threshold" | "query_cap" | "other_query") | null)
export type Kept2 = boolean
export type QueryId5 = string
export type Round5 = number
export type Scorer2 = string
export type Value = number
export type Passages2 = Score[]
export type QueryId6 = string
export type Scored1 = number
export type Scorer3 = string
export type ThresholdDisplay1 = (number | null)
export type Entry = string
export type Passages3 = number[]
export type SourceId5 = string
export type Body = string
export type Cited = number[]
export type Continuations = number
export type Markdown = string
export type References = Reference[]
export type Truncated1 = boolean
export type Warnings4 = string[]
export type Text6 = string
export type RunId6 = string
export type Seq6 = number
export type Stage6 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts6 = string
export type Type6 = "report.delta"
export type RunId7 = string
export type Seq7 = number
export type Stage7 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts7 = string
export type Type7 = "report.snapshot"
export type Note3 = string
export type Planned = number
export type Ran = number
export type Reason2 = ("max rounds" | "no new sources" | "page limit reached" | "model judged coverage sufficient" | "gap step failed")
export type RunId8 = string
export type Seq8 = number
export type Stage8 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts8 = string
export type Type8 = "research.done"
export type ContextTokens1 = (number | "auto" | null)
export type GapContextTokens1 = (number | "auto" | null)
export type MaxPages1 = (number | null)
export type PassagesPerQuery1 = (number | null)
export type ResultsPerQuery1 = (number | null)
export type Rounds1 = (number | null)
export type SubQueries1 = (number | null)
export type Note4 = string
export type Planned1 = number
export type Ran1 = number
export type Reason3 = ("max rounds" | "no new sources" | "page limit reached" | "model judged coverage sufficient" | "gap step failed")
export type Kept3 = number
export type KnownPages = number
export type NewPages = number
export type Note5 = string
export type QueryIds3 = string[]
export type Round6 = number
export type Rounds2 = RoundRecord[]
export type Device2 = string
export type ReleasedStage = ("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write")
export type RunId9 = string
export type Seq9 = number
export type Stage9 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts9 = string
export type Type9 = "resource.released"
export type RunId10 = string
export type Seq10 = number
export type Stage10 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts10 = string
export type Type10 = "resource.waiting"
export type Kept4 = number
export type KnownPages1 = number
export type NewPages1 = number
export type QueryIds4 = string[]
export type Round7 = number
export type RunId11 = string
export type Seq11 = number
export type Stage11 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts11 = string
export type Type11 = "round.done"
export type Stage12 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type RunId12 = string
export type Seq12 = number
export type Stage13 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts12 = string
export type Type12 = "run.cancelled"
export type Cost = number
export type InputTokens1 = number
export type OutputTokens1 = number
export type Requests = number
export type Units = number
export type Depth = (string | null)
export type Profile2 = (string | null)
export type Query2 = string
export type Set1 = string[]
export type Sources1 = (("both" | "web" | "files") | null)
export type Until = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type RunId13 = string
export type Status2 = ("queued" | "running")
export type Cost1 = (number | null)
export type Created = string
export type Depth1 = (string | null)
export type DurationS = (number | null)
export type EndStage = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Error3 = (string | null)
export type ForkFrom = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type LastSeq = number
export type ParentRunId = (string | null)
export type Profile3 = string
export type Query3 = string
export type QueuePosition = (number | null)
export type Changes = string[]
export type CreatedAt = string
export type ForkFrom1 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Overrides = string[]
export type ParentRunId1 = (string | null)
export type Profile4 = string
export type Attachments = string[]
export type Depth2 = (string | null)
export type Query4 = string
export type Sources2 = ("both" | "web" | "files")
export type Until1 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type RunId14 = string
export type Version = number
export type RoundsPlanned = number
export type RoundsRan = (number | null)
export type RunId15 = string
export type Sources3 = ("both" | "web" | "files")
export type Status3 = ("queued" | "running" | "done" | "failed" | "cancelled" | "interrupted")
export type StopReason = (("max rounds" | "no new sources" | "page limit reached" | "model judged coverage sufficient" | "gap step failed") | null)
export type Until2 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Version1 = number
export type CitationMarker1 = ("numeric" | "superscript" | "author-year")
export type Language1 = string
export type ReferenceStyle1 = string
export type Tone1 = string
export type ToneInstructions1 = string
export type Words2 = number
export type Until3 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type RunId16 = string
export type Seq13 = number
export type Stage14 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts13 = string
export type Type13 = "run.done"
export type Error4 = string
export type Stage15 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type RunId17 = string
export type Seq14 = number
export type Stage16 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts14 = string
export type Type14 = "run.failed"
export type Detail3 = string
export type Error5 = string
export type RunId18 = string
export type Status4 = ("queued" | "running" | "done" | "failed" | "cancelled" | "interrupted")
export type Error6 = (string | null)
export type RunDir = string
export type RunId19 = string
export type Status5 = ("done" | "failed" | "cancelled")
export type Position1 = number
export type RunId20 = string
export type Seq15 = number
export type Stage17 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts15 = string
export type Type15 = "run.queued"
export type ParentRunId2 = (string | null)
export type Profile5 = string
export type Query5 = string
export type Until4 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Version2 = number
export type RunId21 = string
export type Seq16 = number
export type Stage18 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts16 = string
export type Type16 = "run.started"
export type Cost2 = (number | null)
export type Created1 = string
export type Depth3 = (string | null)
export type DurationS1 = (number | null)
export type EndStage1 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Error7 = (string | null)
export type ForkFrom2 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type ParentRunId3 = (string | null)
export type Profile6 = string
export type Query6 = string
export type QueuePosition1 = (number | null)
export type RoundsPlanned1 = number
export type RoundsRan1 = (number | null)
export type RunId22 = string
export type Sources4 = ("both" | "web" | "files")
export type Status6 = ("queued" | "running" | "done" | "failed" | "cancelled" | "interrupted")
export type StopReason1 = (("max rounds" | "no new sources" | "page limit reached" | "model judged coverage sufficient" | "gap step failed") | null)
export type Until5 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Version3 = number
export type Failed = Skipped[]
export type Queries4 = QueryScores[]
export type Scorer4 = string
export type Scores = Score[]
export type Failures1 = Skipped[]
export type Hits = Hit[]
export type ChunkId5 = string
export type QueryId7 = string
export type Reason4 = ("source_cap" | "budget")
export type TokensLeft1 = (number | null)
export type TokensNeeded1 = (number | null)
export type Sources5 = ("both" | "web" | "files")
export type Expires = (string | null)
export type Method1 = ("cookie" | "token" | "none")
export type Since = (string | null)
export type TokenName = (string | null)
export type ChunkId6 = string
export type HeadingPath3 = string[]
export type Position2 = number
export type Queries5 = ChunkQueryFate[]
export type RemovedBefore = number
export type Text7 = string
export type Chunks1 = SourceChunk[]
export type Queries6 = Query1[]
export type QueryCap = number
export type SourceCap = number
export type Threshold = (number | null)
export type Truncated2 = boolean
export type CopiedFrom = (string | null)
export type Count = number
export type Passthrough1 = string[]
export type Provider2 = (string | null)
export type Round8 = number
export type Seconds = number
export type Skipped2 = boolean
export type Unfetched1 = number
export type Warnings5 = string[]
export type RunId23 = string
export type Seq17 = number
export type Stage19 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts17 = string
export type Type17 = "stage.done"
export type Error8 = string
export type Next = string
export type RunId24 = string
export type Seq18 = number
export type Stage20 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts18 = string
export type Type18 = "stage.failed"
export type Done = number
export type Failed1 = number
export type Round9 = number
export type Total = number
export type RunId25 = string
export type Seq19 = number
export type Stage21 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts19 = string
export type Type19 = "stage.progress"
export type Device3 = (string | null)
export type Provider3 = string
export type Round10 = number
export type RunId26 = string
export type Seq20 = number
export type Stage22 = (("load" | "plan" | "search" | "fetch" | "chunk" | "prefilter" | "score" | "gap" | "select" | "write") | null)
export type Ts20 = string
export type Type20 = "stage.started"
export type Name3 = string
export type Id1 = string
export type Name4 = string
export type Token = string
export type Created2 = string
export type Id2 = string
export type LastUsed = (string | null)
export type Masked = string
export type Name5 = string

export interface WosarcherContracts {
[k: string]: unknown
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ApiError".
 */
export interface ApiError {
detail: Detail
error: Error
}
/**
 * Attachment bytes read by `attachments.collect` or received by the server.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Attachment".
 */
export interface Attachment {
data: Data
name: Name
}
/**
 * A chunk and query pair that reaches the score stage.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Candidate".
 */
export interface Candidate {
chunk_id: ChunkId
passthrough?: Passthrough
prefilter?: Prefilter
query_id: QueryId
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Chunk".
 */
export interface Chunk {
block_ids?: BlockIds
chunk_id: ChunkId1
heading_path?: HeadingPath
page_id?: PageId
position: Position
source_id: SourceId
text: Text
}
/**
 * Where a chunk ended: cited, skipped by select, kept, or dropped before.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ChunkFate".
 */
export interface ChunkFate {
display?: Display
kept_in_query?: KeptInQuery
kind: Kind
n?: N
query_id?: QueryId1
rank?: Rank
ranked?: Ranked
tokens_left?: TokensLeft
tokens_needed?: TokensNeeded
}
/**
 * One chunk and sub-query pair as the Source dialog shows it.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ChunkQueryFate".
 */
export interface ChunkQueryFate {
display?: Display1
query_id: QueryId2
state: State
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ChunkResult".
 */
export interface ChunkResult {
chunks: Chunks
duplicates?: Duplicates
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Completion".
 */
export interface Completion {
input_tokens?: InputTokens
output_tokens?: OutputTokens
text: Text1
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Context".
 */
export interface Context {
budget_tokens: BudgetTokens
passages: Passages
query: Query
sources: Sources
used_tokens: UsedTokens
}
/**
 * One selected chunk; `n` is its citation number.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Passage".
 */
export interface Passage {
block_ids?: BlockIds1
chunk_id: ChunkId2
display?: Display2
heading_path?: HeadingPath1
n: N1
page_id?: PageId1
query_id: QueryId3
scorer: Scorer
source_id: SourceId1
text: Text2
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Source".
 */
export interface Source {
author?: Author
kind: Kind1
published?: Published
source_id: SourceId2
title: Title
uri: Uri
}
/**
 * One depth preset as `GET /api/depths` lists it.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "DepthInfo".
 */
export interface DepthInfo {
description: Description
name: Name1
values: DepthValues
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "DepthValues".
 */
export interface DepthValues {
context_tokens: ContextTokens
gap_context_tokens: GapContextTokens
max_pages: MaxPages
passages_per_query: PassagesPerQuery
queries_per_round: QueriesPerRound
results_per_query: ResultsPerQuery
rounds: Rounds
sub_queries: SubQueries
words?: Words
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "DoctorReport".
 */
export interface DoctorReport {
gpu_policy?: GpuPolicy
providers?: Providers
warnings?: Warnings
}
/**
 * One row of `wosarcher doctor`: a configured block and its probe result.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ProviderHealth".
 */
export interface ProviderHealth {
base_url?: BaseUrl
block: Block
context_window?: ContextWindow
device?: Device
error?: Error1
latency_ms?: LatencyMs
model?: Model
note?: Note
provider: Provider
release?: Release
status: Status
unload?: Unload
}
/**
 * The embedding model identity used in cache keys.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "EmbedderInfo".
 */
export interface EmbedderInfo {
dimension: Dimension
model: Model1
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "FetchResult".
 */
export interface FetchResult {
failures?: Failures
pages: Pages
unfetched?: Unfetched
}
/**
 * An item that did not make it: a failed search or fetch, or a skipped file.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Skipped".
 */
export interface Skipped {
item: Item
reason: Reason
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Page".
 */
export interface Page {
format?: Format
query_ids?: QueryIds
rank?: Rank1
round?: Round
source: Source
text: Text3
truncated?: Truncated
}
/**
 * The body of `POST /api/runs/{id}/fork`.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ForkCreate".
 */
export interface ForkCreate {
from: From
profile?: Profile
set?: Set
writing?: WritingPatch
}
/**
 * Any subset of the writing options; unset fields keep the value from the layer below.
 */
export interface WritingPatch {
citation_marker?: CitationMarker
language?: Language
reference_style?: ReferenceStyle
tone?: Tone
tone_instructions?: ToneInstructions
words?: Words1
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "GapReady".
 */
export interface GapReady {
data: GapReadyData
run_id: RunId
seq: Seq
stage?: Stage
ts: Ts
type?: Type
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "GapReadyData".
 */
export interface GapReadyData {
note: Note1
queries: Queries
round: Round2
stop: Stop
}
/**
 * `q0` is the main query, whose text is the planner's topic line; `q1`, `q2`, ... are sub-queries.
 * 
 * The user's query stays on the run request; `q0` holds the short text that is searched and ranked against.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Query".
 */
export interface Query1 {
id: Id
round?: Round1
text: Text4
}
/**
 * The gap step's reply after a round: validated follow-ups, a note, and the advisory stop flag.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "GapResult".
 */
export interface GapResult {
note?: Note2
queries: Queries1
stop?: Stop1
}
/**
 * Body of `POST /api/providers/health/check`; no blocks means every block.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "HealthCheckRequest".
 */
export interface HealthCheckRequest {
blocks?: Blocks
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "HealthReport".
 */
export interface HealthReport {
checks: Checks
gpu_policy?: GpuPolicy1
profile: Profile1
warnings?: Warnings1
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ProviderCheck".
 */
export interface ProviderCheck {
checked_at?: CheckedAt
detail?: Detail1
device?: Device1
latency_ms?: LatencyMs1
model?: Model2
provider: Provider1
release?: Release1
role: Role
status: Status1
url?: Url
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Hit".
 */
export interface Hit {
query_ids: QueryIds1
rank: Rank2
round?: Round3
snippet: Snippet
title: Title1
url: Url1
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "HitFound".
 */
export interface HitFound {
data: HitFoundData
run_id: RunId1
seq: Seq1
stage?: Stage1
ts: Ts1
type?: Type1
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "HitFoundData".
 */
export interface HitFoundData {
query_ids: QueryIds2
title: Title2
url: Url2
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "KeptPassage".
 */
export interface KeptPassage {
chunk_id: ChunkId3
display: Display3
heading_path?: HeadingPath2
source_id: SourceId3
text: Text5
title: Title3
uri: Uri1
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "LoadResult".
 */
export interface LoadResult {
pages: Pages1
skipped?: Skipped1
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "LoginError".
 */
export interface LoginError {
attempts_left?: AttemptsLeft
detail: Detail2
error: Error2
retry_after?: RetryAfter
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "LoginRequest".
 */
export interface LoginRequest {
password: Password
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Message".
 */
export interface Message {
content: Content
role: Role1
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "PageFailed".
 */
export interface PageFailed {
data: PageFailedData
run_id: RunId2
seq: Seq2
stage?: Stage2
ts: Ts2
type?: Type2
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "PageFailedData".
 */
export interface PageFailedData {
reason: Reason1
url: Url3
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "PageFetched".
 */
export interface PageFetched {
data: PageFetchedData
run_id: RunId3
seq: Seq3
stage?: Stage3
ts: Ts3
type?: Type3
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "PageFetchedData".
 */
export interface PageFetchedData {
cached: Cached
chars: Chars
round?: Round4
source_id: SourceId4
title: Title4
url: Url4
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "PassagesScored".
 */
export interface PassagesScored {
data: PassagesScoredData
run_id: RunId4
seq: Seq4
stage?: Stage4
ts: Ts4
type?: Type4
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "PassagesScoredData".
 */
export interface PassagesScoredData {
kept: Kept
passages: Passages1
query_id: QueryId4
scored: Scored
scorer: Scorer1
threshold_display: ThresholdDisplay
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Plan".
 */
export interface Plan {
queries: Queries2
warnings?: Warnings2
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "PlanReady".
 */
export interface PlanReady {
data: PlanReadyData
run_id: RunId5
seq: Seq5
stage?: Stage5
ts: Ts5
type?: Type5
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "PlanReadyData".
 */
export interface PlanReadyData {
queries: Queries3
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "PrefilterResult".
 */
export interface PrefilterResult {
candidates: Candidates
method: Method
warnings?: Warnings3
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ProfileInfo".
 */
export interface ProfileInfo {
active: Active
context_window?: ContextWindow1
description?: Description1
max_output_tokens?: MaxOutputTokens
name: Name2
prompt_reserve_tokens?: PromptReserveTokens
source: Source1
}
/**
 * One query's scoring report.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "QueryScores".
 */
export interface QueryScores {
kept: Kept1
passages: Passages2
query_id: QueryId6
scored: Scored1
scorer: Scorer3
threshold_display: ThresholdDisplay1
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Score".
 */
export interface Score {
chunk_id: ChunkId4
display?: Display4
dropped?: Dropped
kept?: Kept2
query_id: QueryId5
round?: Round5
scorer: Scorer2
value: Value
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Reference".
 */
export interface Reference {
entry: Entry
passages: Passages3
source_id: SourceId5
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "Report".
 */
export interface Report {
body: Body
cited: Cited
continuations?: Continuations
markdown: Markdown
references: References
truncated?: Truncated1
warnings?: Warnings4
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ReportDelta".
 */
export interface ReportDelta {
data: ReportTextData
run_id: RunId6
seq: Seq6
stage?: Stage6
ts: Ts6
type?: Type6
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ReportTextData".
 */
export interface ReportTextData {
text: Text6
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ReportSnapshot".
 */
export interface ReportSnapshot {
data: ReportTextData
run_id: RunId7
seq: Seq7
stage?: Stage7
ts: Ts7
type?: Type7
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ResearchDone".
 */
export interface ResearchDone {
data: ResearchDoneData
run_id: RunId8
seq: Seq8
stage?: Stage8
ts: Ts8
type?: Type8
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ResearchDoneData".
 */
export interface ResearchDoneData {
note: Note3
planned: Planned
ran: Ran
reason: Reason2
}
/**
 * Typed research values; each sets one key (`config.RESEARCH_KEYS`).
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ResearchPatch".
 */
export interface ResearchPatch {
context_tokens?: ContextTokens1
gap_context_tokens?: GapContextTokens1
max_pages?: MaxPages1
passages_per_query?: PassagesPerQuery1
results_per_query?: ResultsPerQuery1
rounds?: Rounds1
sub_queries?: SubQueries1
}
/**
 * `research.json`: the rounds of a multi-round run and why research stopped.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ResearchRecord".
 */
export interface ResearchRecord {
note?: Note4
planned: Planned1
ran: Ran1
reason: Reason3
rounds: Rounds2
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RoundRecord".
 */
export interface RoundRecord {
kept?: Kept3
known_pages?: KnownPages
new_pages?: NewPages
note?: Note5
query_ids: QueryIds3
round: Round6
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ResourceData".
 */
export interface ResourceData {
device: Device2
released_stage: ReleasedStage
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ResourceReleased".
 */
export interface ResourceReleased {
data: ResourceData
run_id: RunId9
seq: Seq9
stage?: Stage9
ts: Ts9
type?: Type9
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ResourceWaiting".
 */
export interface ResourceWaiting {
data: ResourceData
run_id: RunId10
seq: Seq10
stage?: Stage10
ts: Ts10
type?: Type10
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RoundDone".
 */
export interface RoundDone {
data: RoundDoneData
run_id: RunId11
seq: Seq11
stage?: Stage11
ts: Ts11
type?: Type11
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RoundDoneData".
 */
export interface RoundDoneData {
kept: Kept4
known_pages: KnownPages1
new_pages: NewPages1
query_ids: QueryIds4
round: Round7
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunCancelled".
 */
export interface RunCancelled {
data: RunCancelledData
run_id: RunId12
seq: Seq12
stage?: Stage13
ts: Ts12
type?: Type12
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunCancelledData".
 */
export interface RunCancelledData {
stage: Stage12
}
/**
 * `costs.json`.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunCosts".
 */
export interface RunCosts {
providers: Providers1
stages: Stages
total: UsageTotals
}
export interface Providers1 {
[k: string]: UsageTotals
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "UsageTotals".
 */
export interface UsageTotals {
cost?: Cost
input_tokens?: InputTokens1
output_tokens?: OutputTokens1
requests?: Requests
units?: Units
}
export interface Stages {
[k: string]: UsageTotals
}
/**
 * The `request` field of `POST /api/runs`.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunCreate".
 */
export interface RunCreate {
depth?: Depth
profile?: Profile2
query: Query2
research?: ResearchPatch1
set?: Set1
sources?: Sources1
until?: Until
writing?: WritingPatch1
}
/**
 * Typed research values; each sets one key (`config.RESEARCH_KEYS`).
 */
export interface ResearchPatch1 {
context_tokens?: ContextTokens1
gap_context_tokens?: GapContextTokens1
max_pages?: MaxPages1
passages_per_query?: PassagesPerQuery1
results_per_query?: ResultsPerQuery1
rounds?: Rounds1
sub_queries?: SubQueries1
}
/**
 * Any subset of the writing options; unset fields keep the value from the layer below.
 */
export interface WritingPatch1 {
citation_marker?: CitationMarker
language?: Language
reference_style?: ReferenceStyle
tone?: Tone
tone_instructions?: ToneInstructions
words?: Words1
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunCreated".
 */
export interface RunCreated {
run_id: RunId13
status: Status2
}
/**
 * `GET /api/runs/{id}`: the summary plus the stored record, costs, and the last logged `seq`.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunDetail".
 */
export interface RunDetail {
cost?: Cost1
costs?: (RunCosts | null)
created: Created
depth?: Depth1
duration_s?: DurationS
end_stage?: EndStage
error?: Error3
fork_from?: ForkFrom
last_seq?: LastSeq
parent_run_id?: ParentRunId
profile: Profile3
query: Query3
queue_position?: QueuePosition
request?: (RunRecord | null)
rounds_planned?: RoundsPlanned
rounds_ran?: RoundsRan
run_id: RunId15
sources?: Sources3
status: Status3
stop_reason?: StopReason
until?: Until2
version?: Version1
writing?: WritingOptions
}
/**
 * `request.json`: what a run was asked, with which configuration, and where it came from.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunRecord".
 */
export interface RunRecord {
changes?: Changes
created_at: CreatedAt
fork_from?: ForkFrom1
overrides?: Overrides
parent_run_id?: ParentRunId1
profile: Profile4
request: RunRequest
run_id: RunId14
settings: Settings
version?: Version
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunRequest".
 */
export interface RunRequest {
attachments?: Attachments
depth?: Depth2
query: Query4
sources?: Sources2
until?: Until1
}
export interface Settings {
[k: string]: unknown
}
export interface WritingOptions {
citation_marker?: CitationMarker1
language?: Language1
reference_style?: ReferenceStyle1
tone?: Tone1
tone_instructions?: ToneInstructions1
words?: Words2
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunDone".
 */
export interface RunDone {
data: RunDoneData
run_id: RunId16
seq: Seq13
stage?: Stage14
ts: Ts13
type?: Type13
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunDoneData".
 */
export interface RunDoneData {
totals: UsageTotals
until: Until3
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunFailed".
 */
export interface RunFailed {
data: RunFailedData
run_id: RunId17
seq: Seq14
stage?: Stage16
ts: Ts14
type?: Type14
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunFailedData".
 */
export interface RunFailedData {
error: Error4
stage: Stage15
}
/**
 * The 409 body of `POST /api/runs/{id}/cancel` for a run that is neither queued nor running.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunNotActive".
 */
export interface RunNotActive {
detail: Detail3
error: Error5
run_id: RunId18
status: Status4
}
/**
 * What `wosarcher run --json` and `wosarcher fork --json` print.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunOutput".
 */
export interface RunOutput {
context?: (Context | null)
error?: Error6
report?: (Report | null)
run_dir: RunDir
run_id: RunId19
status: Status5
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunQueued".
 */
export interface RunQueued {
data: RunQueuedData
run_id: RunId20
seq: Seq15
stage?: Stage17
ts: Ts15
type?: Type15
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunQueuedData".
 */
export interface RunQueuedData {
position: Position1
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunStarted".
 */
export interface RunStarted {
data: RunStartedData
run_id: RunId21
seq: Seq16
stage?: Stage18
ts: Ts16
type?: Type16
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunStartedData".
 */
export interface RunStartedData {
parent_run_id: ParentRunId2
profile: Profile5
query: Query5
until: Until4
version: Version2
}
/**
 * One run as `wosarcher runs --json` and `GET /api/runs` list it.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "RunSummary".
 */
export interface RunSummary {
cost?: Cost2
created: Created1
depth?: Depth3
duration_s?: DurationS1
end_stage?: EndStage1
error?: Error7
fork_from?: ForkFrom2
parent_run_id?: ParentRunId3
profile: Profile6
query: Query6
queue_position?: QueuePosition1
rounds_planned?: RoundsPlanned1
rounds_ran?: RoundsRan1
run_id: RunId22
sources?: Sources4
status: Status6
stop_reason?: StopReason1
until?: Until5
version?: Version3
writing?: WritingOptions1
}
export interface WritingOptions1 {
citation_marker?: CitationMarker1
language?: Language1
reference_style?: ReferenceStyle1
tone?: Tone1
tone_instructions?: ToneInstructions1
words?: Words2
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ScoreResult".
 */
export interface ScoreResult {
failed?: Failed
queries: Queries4
scorer: Scorer4
scores: Scores
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "SearchResult".
 */
export interface SearchResult {
failures?: Failures1
hits: Hits
}
/**
 * A kept passage that select did not take.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "SelectSkip".
 */
export interface SelectSkip {
chunk_id: ChunkId5
query_id: QueryId7
reason: Reason4
tokens_left?: TokensLeft1
tokens_needed?: TokensNeeded1
}
/**
 * Global defaults for runs started by the server (`server-settings.json`).
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "ServerSettings".
 */
export interface ServerSettings {
sources?: Sources5
writing?: WritingOptions2
}
export interface WritingOptions2 {
citation_marker?: CitationMarker1
language?: Language1
reference_style?: ReferenceStyle1
tone?: Tone1
tone_instructions?: ToneInstructions1
words?: Words2
}
/**
 * `GET /api/session`: how this request is authenticated.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "SessionInfo".
 */
export interface SessionInfo {
expires?: Expires
method: Method1
since?: Since
token_name?: TokenName
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "SourceChunk".
 */
export interface SourceChunk {
chunk_id: ChunkId6
fate: ChunkFate
heading_path?: HeadingPath3
position: Position2
queries: Queries5
removed_before?: RemovedBefore
text: Text7
}
/**
 * `GET /api/runs/{id}/sources/{source_id}`: one source's chunks and their fates.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "SourceView".
 */
export interface SourceView {
chunks: Chunks1
queries: Queries6
query_cap: QueryCap
source: Source
source_cap: SourceCap
threshold?: Threshold
truncated?: Truncated2
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "StageDone".
 */
export interface StageDone {
data: StageDoneData
run_id: RunId23
seq: Seq17
stage?: Stage19
ts: Ts17
type?: Type17
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "StageDoneData".
 */
export interface StageDoneData {
copied_from?: CopiedFrom
count: Count
passthrough?: Passthrough1
provider?: Provider2
round?: Round8
seconds: Seconds
skipped?: Skipped2
unfetched?: Unfetched1
usage?: UsageTotals1
warnings?: Warnings5
}
export interface UsageTotals1 {
cost?: Cost
input_tokens?: InputTokens1
output_tokens?: OutputTokens1
requests?: Requests
units?: Units
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "StageFailed".
 */
export interface StageFailed {
data: StageFailedData
run_id: RunId24
seq: Seq18
stage?: Stage20
ts: Ts18
type?: Type18
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "StageFailedData".
 */
export interface StageFailedData {
error: Error8
next: Next
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "StageProgress".
 */
export interface StageProgress {
data: StageProgressData
run_id: RunId25
seq: Seq19
stage?: Stage21
ts: Ts19
type?: Type19
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "StageProgressData".
 */
export interface StageProgressData {
done: Done
failed: Failed1
round?: Round9
total: Total
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "StageStarted".
 */
export interface StageStarted {
data: StageStartedData
run_id: RunId26
seq: Seq20
stage?: Stage22
ts: Ts20
type?: Type20
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "StageStartedData".
 */
export interface StageStartedData {
device: Device3
provider: Provider3
round?: Round10
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "TokenCreate".
 */
export interface TokenCreate {
name: Name3
}
/**
 * The new token, shown only in this response.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "TokenCreated".
 */
export interface TokenCreated {
id: Id1
name: Name4
token: Token
}
/**
 * A stored API token as listed; never the token or its hash.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "TokenInfo".
 */
export interface TokenInfo {
created: Created2
id: Id2
last_used?: LastUsed
masked: Masked
name: Name5
}
/**
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "WritingOptions".
 */
export interface WritingOptions3 {
citation_marker?: CitationMarker1
language?: Language1
reference_style?: ReferenceStyle1
tone?: Tone1
tone_instructions?: ToneInstructions1
words?: Words2
}
/**
 * Any subset of the writing options; unset fields keep the value from the layer below.
 * 
 * This interface was referenced by `WosarcherContracts`'s JSON-Schema
 * via the `definition` "WritingPatch".
 */
export interface WritingPatch2 {
citation_marker?: CitationMarker
language?: Language
reference_style?: ReferenceStyle
tone?: Tone
tone_instructions?: ToneInstructions
words?: Words1
}
