// Generates src/api/generated.ts from `wosarcher schema` (the JSON Schema of the contracts,
// event models, and server request and response models).
//
//   node scripts/gen-types.mjs           write src/api/generated.ts
//   node scripts/gen-types.mjs --check   exit 1 when the committed file is out of date
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const web = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const target = resolve(web, "src/api/generated.ts");
const HINT = "src/api/generated.ts is out of date; run pnpm --dir web run gen:types";
const BANNER = "/* Generated by web/scripts/gen-types.mjs from `wosarcher schema`. Do not edit. */";

export function readSchema() {
  const out = execFileSync("uv", ["run", "--frozen", "wosarcher", "schema"], {
    cwd: resolve(web, ".."),
    encoding: "utf8",
    stdio: ["ignore", "pipe", "inherit"],
  });
  return JSON.parse(out);
}

export function generate(schema) {
  return compile(schema, "Schema", {
    bannerComment: BANNER,
    unreachableDefinitions: true,
    additionalProperties: false,
    format: false,
  });
}

/** Returns the exit code: 0 when written or up to date, 1 when `check` finds drift. */
export async function run({ check, schema = readSchema(), file = target, log = console.error }) {
  const text = await generate(schema);
  if (!check) {
    writeFileSync(file, text);
    return 0;
  }
  let current = "";
  try {
    current = readFileSync(file, "utf8");
  } catch {}
  if (current === text) return 0;
  log(HINT);
  return 1;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  process.exitCode = await run({ check: process.argv.includes("--check") });
}
