from itertools import pairwise
from typing import Literal

from wosarcher.models import Page, Source
from wosarcher.stages.chunk import boilerplate, chunk, clean, sections


def page(
    text: str, source_id: str = "s1", page_format: str = "markdown", kind: Literal["web", "file"] = "file"
) -> Page:
    source = Source(source_id=source_id, kind=kind, uri=f"{source_id}.md", title=source_id)
    return Page.model_validate({"source": source, "text": text, "format": page_format})


def words(count: int, seed: str = "w") -> str:
    """`count` characters of distinct words, so no two chunks are duplicates."""
    text = " ".join(f"{seed}{n:04d}" for n in range(count // 6 + 1))
    return text[:count]


def web(text: str, source_id: str = "s1") -> Page:
    return page(text, source_id, kind="web")


def sentences(count: int, seed: str = "w") -> str:
    """About `count` characters of distinct words ending in a full stop."""
    return words(count - 1, seed) + "."


def test_nested_heading_path() -> None:
    found = sections("before\n\n## Results\nr\n\n### Latency\nl\n\n## Other\no\n")
    assert [(s.path, s.text.strip()) for s in found] == [
        ((), "before"),
        (("Results",), "r"),
        (("Results", "Latency"), "l"),
        (("Other",), "o"),
    ]


def test_heading_in_code_does_not_split() -> None:
    found = sections("# A\n```\n# not a heading\n```\n")
    assert [s.path for s in found] == [("A",)]


def test_setext_heading() -> None:
    assert [s.path for s in sections("Title\n=====\ntext\n")] == [("Title",)]


def test_link_and_image() -> None:
    assert clean("see [the docs](https://x.example/d) ![chart](data:image/png;base64,AAAA)") == "see the docs chart"


def test_comment_img_and_autolink_removed() -> None:
    assert clean('a <!-- generated by tool --> b <img src="data:x"> c <https://x.example>') == "a b c"


def test_two_short_sections_merge() -> None:
    result = chunk([page(f"# A\n{words(200, 'a')}\n\n# B\n{words(200, 'b')}\n")], size=1800, overlap=150, min_chars=500)
    assert len(result.chunks) == 1
    assert result.chunks[0].heading_path == []
    assert result.chunks[0].text.startswith("A\n\na0000")
    assert "\n\nB\n\nb0000" in result.chunks[0].text


def test_two_sections() -> None:
    result = chunk(
        [page(f"# A\n{words(1000, 'a')}\n\n# B\n{words(1000, 'b')}\n")], size=1800, overlap=150, min_chars=500
    )
    assert [c.heading_path for c in result.chunks] == [["A"], ["B"]]
    assert all("# " not in c.text for c in result.chunks)


def test_merging_off() -> None:
    result = chunk([page(f"# A\n{words(200, 'a')}\n\n# B\n{words(200, 'b')}\n")], size=1800, overlap=150, min_chars=0)
    assert [c.heading_path for c in result.chunks] == [["A"], ["B"]]


def test_merged_siblings() -> None:
    text = f"## Requisitos\n\n### Presencial\n{words(150, 'p')}\n\n### Virtual\n{words(150, 'v')}\n"
    [only] = chunk([page(text)], size=1800, overlap=150, min_chars=500).chunks
    assert only.heading_path == ["Requisitos"]
    assert only.text.split("\n\n") == ["Presencial", words(150, "p").strip(), "Virtual", words(150, "v").strip()]


def test_short_page_stays() -> None:
    text = "Pague la tasa en la ventanilla de la municipalidad antes del viernes."
    result = chunk([web(text)], size=1800, overlap=150, min_chars=500)
    assert [c.text for c in result.chunks] == [text]


def test_merge_stops_at_size_limit() -> None:
    result = chunk(
        [page(f"# A\n{words(300, 'a')}\n\n# B\n{words(1700, 'b')}\n")], size=1800, overlap=150, min_chars=500
    )
    assert [c.heading_path for c in result.chunks] == [["A"], ["B"]]


def test_short_tail_joins_previous_group() -> None:
    result = chunk([page(f"# A\n{words(900, 'a')}\n\n# B\n{words(120, 'b')}\n")], size=1800, overlap=150, min_chars=500)
    assert len(result.chunks) == 1
    assert words(120, "b").strip() in result.chunks[0].text


def test_long_section() -> None:
    result = chunk([page(words(4000))], size=1800, overlap=150, min_chars=500)
    texts = [c.text for c in result.chunks]
    assert len(texts) == 3
    assert all(len(text) <= 1800 for text in texts)
    for previous, current in pairwise(texts):
        assert current[:20] in previous[-150:]


def test_no_short_last_chunk() -> None:
    texts = [c.text for c in chunk([page(words(1900))], size=1800, overlap=150, min_chars=500).chunks]
    assert len(texts) == 2
    assert len(texts[1]) >= 500


def test_empty_sections_give_no_chunk() -> None:
    result = chunk([page("# A\n\n<!-- only a comment -->\n\n# B\n")], size=1800, overlap=150, min_chars=500)
    assert result.chunks == []


def test_skip_link_dropped() -> None:
    text = f"Saltar a contenido principal\n\n# Trámite\n{sentences(300)}\n"
    result = chunk([web(text)], size=1800, overlap=150, min_chars=500)
    assert all("Saltar" not in c.text for c in result.chunks)
    assert result.boilerplate == 1


def test_link_list() -> None:
    links = "\n".join(f"- [Enlace {n}](https://x.example/{n})" for n in range(6))
    assert boilerplate(links)


def test_bare_url() -> None:
    assert boilerplate("Pasar al contenido principal https://www.munlima.gob.pe/#main")


def test_short_sentence_kept() -> None:
    assert not boilerplate("Código municipal y clave virtual.")


def test_short_list_kept() -> None:
    assert not boilerplate(
        "*   [Casilla electrónica judicial](https://www.gob.pe/13976-obtener-casilla-judicial-electronica)"
    )


def test_attachment_untouched() -> None:
    result = chunk(
        [page(f"Saltar a contenido principal\n\n# Trámite\n{sentences(300)}\n")], size=1800, overlap=150, min_chars=500
    )
    assert "Saltar a contenido principal" in result.chunks[0].text
    assert result.boilerplate == 0


def test_navigation_only_page() -> None:
    text = "Inicio\n\n# Menú\n- [Trámites](https://x.example/t)\n- [Servicios municipales](https://x.example/s)\n"
    result = chunk([web(text)], size=1800, overlap=150, min_chars=500)
    assert [c.text for c in result.chunks] == ["- Trámites\n- Servicios municipales"]
    assert result.boilerplate == 1


def test_pdf_ingest_anchors() -> None:
    text = "<!-- page: 3 -->\nfirst\n\n# Part\n<!-- page: 4 -->\n<!-- a: p4-b1 -->\nsecond\n\n# Next\nthird\n"
    result = chunk([page(text, page_format="pdf-ingest")], size=1800, overlap=150, min_chars=0)
    assert [(c.text, c.page_id, c.block_ids) for c in result.chunks] == [
        ("first", "3", []),
        ("second", "4", ["p4-b1"]),
        ("third", "4", []),
    ]


def test_pdf_ingest_anchors_merged() -> None:
    text = "<!-- page: 3 -->\nfirst\n\n# Part\n<!-- page: 4 -->\n<!-- a: p4-b1 -->\nsecond\n\n# Next\nthird\n"
    [only] = chunk([page(text, page_format="pdf-ingest")], size=1800, overlap=150, min_chars=500).chunks
    assert (only.text, only.page_id, only.block_ids) == ("first\n\nPart\n\nsecond\n\nNext\n\nthird", "3", ["p4-b1"])


def test_ids_independent_of_other_pages() -> None:
    alone = chunk([page("# A\none\n\n# B\ntwo\n", "s2")], size=1800, overlap=150, min_chars=0)
    together = chunk(
        [page("# X\nother\n", "s1"), page("# A\none\n\n# B\ntwo\n", "s2")], size=1800, overlap=150, min_chars=0
    )
    assert [c.chunk_id for c in alone.chunks] == [c.chunk_id for c in together.chunks if c.source_id == "s2"]
    assert [c.position for c in alone.chunks] == [0, 1]


def test_same_paragraph_on_two_pages() -> None:
    result = chunk(
        [page("Hello, World! Batteries.", "s1"), page("hello   world -- batteries", "s2")],
        size=1800,
        overlap=150,
        min_chars=500,
    )
    assert [c.source_id for c in result.chunks] == ["s1"]
    assert result.duplicates == 1
