from itertools import pairwise

from wosarcher.models import Page, Source
from wosarcher.stages.chunk import chunk, clean, sections


def page(text: str, source_id: str = "s1", page_format: str = "markdown") -> Page:
    source = Source(source_id=source_id, kind="file", uri=f"{source_id}.md", title=source_id)
    return Page.model_validate({"source": source, "text": text, "format": page_format})


def words(count: int, seed: str = "w") -> str:
    """`count` characters of distinct words, so no two chunks are duplicates."""
    text = " ".join(f"{seed}{n:04d}" for n in range(count // 6 + 1))
    return text[:count]


def test_nested_heading_path() -> None:
    found = sections("before\n\n## Results\nr\n\n### Latency\nl\n\n## Other\no\n")
    assert [(s.path, s.text.strip()) for s in found] == [
        ((), "before"),
        (("Results",), "r"),
        (("Results", "Latency"), "l"),
        (("Other",), "o"),
    ]


def test_heading_in_code_does_not_split() -> None:
    found = sections("# A\n```\n# not a heading\n```\n")
    assert [s.path for s in found] == [("A",)]


def test_setext_heading() -> None:
    assert [s.path for s in sections("Title\n=====\ntext\n")] == [("Title",)]


def test_link_and_image() -> None:
    assert clean("see [the docs](https://x.example/d) ![chart](data:image/png;base64,AAAA)") == "see the docs chart"


def test_comment_img_and_autolink_removed() -> None:
    assert clean('a <!-- generated by tool --> b <img src="data:x"> c <https://x.example>') == "a b c"


def test_two_sections() -> None:
    result = chunk([page(f"# A\n{words(200, 'a')}\n\n# B\n{words(200, 'b')}\n")], size=1000, overlap=100)
    assert [c.heading_path for c in result.chunks] == [["A"], ["B"]]
    assert all("# " not in c.text for c in result.chunks)


def test_long_section() -> None:
    result = chunk([page(words(2500))], size=1000, overlap=100)
    texts = [c.text for c in result.chunks]
    assert len(texts) == 3
    assert all(len(text) <= 1000 for text in texts)
    for previous, current in pairwise(texts):
        assert current[:20] in previous[-100:]


def test_empty_sections_give_no_chunk() -> None:
    result = chunk([page("# A\n\n<!-- only a comment -->\n\n# B\n")], size=1000, overlap=100)
    assert result.chunks == []


def test_pdf_ingest_anchors() -> None:
    text = "<!-- page: 3 -->\nfirst\n\n# Part\n<!-- page: 4 -->\n<!-- a: p4-b1 -->\nsecond\n\n# Next\nthird\n"
    result = chunk([page(text, page_format="pdf-ingest")], size=1000, overlap=100)
    assert [(c.text, c.page_id, c.block_ids) for c in result.chunks] == [
        ("first", "3", []),
        ("second", "4", ["p4-b1"]),
        ("third", "4", []),
    ]


def test_ids_independent_of_other_pages() -> None:
    alone = chunk([page("# A\none\n\n# B\ntwo\n", "s2")], size=1000, overlap=100)
    together = chunk([page("# X\nother\n", "s1"), page("# A\none\n\n# B\ntwo\n", "s2")], size=1000, overlap=100)
    assert [c.chunk_id for c in alone.chunks] == [c.chunk_id for c in together.chunks if c.source_id == "s2"]
    assert [c.position for c in alone.chunks] == [0, 1]


def test_same_paragraph_on_two_pages() -> None:
    result = chunk(
        [page("Hello, World! Batteries.", "s1"), page("hello   world -- batteries", "s2")], size=1000, overlap=100
    )
    assert [c.source_id for c in result.chunks] == ["s1"]
    assert result.duplicates == 1
